# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: pytest

on:
  push:
    paths-ignore:
      - '**/README.md'
      - '**/Dockerfile'
      - '**/.gitignore'
      - '**/.dockerignore'
      - '.github/workflows/docker-publish.yml'
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    container:
      image: python:3.10.5
      options: --user root
    steps:
    - uses: actions/checkout@v3
    - name: Install application dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install testing packages
      run: |
        bash tests/install_packages.sh
    - name: Run testing suite
      run: |
        bash tests/run_tests.sh
